/**
 * @typedef {Object} TechnicalQuestion
 * @property {string} question - The technical question generated by the AI.
 * @property {string} intent - The core concept or intent being tested by this question.
 * @property {string} answer - The expected ideal answer for reference.
 * */

/**
 * @typedef {Object} BehavioralQuestion
 * @property {string} question - The behavioral/situational question matching the job role.
 * @property {string} intent - The soft skill or trait being evaluated.
 * @property {string} answer - Suggested structure or points for the response (e.g., STAR method).
 * */

/**
 * @typedef {Object} SkillGap
 * @property {string} skill - The specific skill or technology missing from the resume.
 * @property {('low'|'medium'|'high')} severity - The critical impact level of the missing skill relative to the job.
 * */

/**
 * @typedef {Object} PreparationDay
 * @property {number} day - The specific milestone or day number in the roadmap.
 * @property {string} focus - The core subject or technical area assigned to this day.
 * @property {string[]} tasks - Array of actionable training steps, readings, or coding exercises.
 * */

const mongoose = require('mongoose');

const technicalQuestionSchema = new mongoose.Schema({
    question: {
        type: String,
        required: [ true, "Technical question is required" ]
    },
    intention: {
        type: String,
        required: [ true, "Intention is required" ]
    },
    answer: {
        type: String,
        required: [ true, "Answer is required" ]
    }
}, {
    _id: false
})

const behavioralQuestionSchema = new mongoose.Schema({
    question: {
        type: String,
        required: [ true, "Technical question is required" ]
    },
    intention: {
        type: String,
        required: [ true, "Intention is required" ]
    },
    answer: {
        type: String,
        required: [ true, "Answer is required" ]
    }
}, {
    _id: false
})

const skillGapSchema = new mongoose.Schema({
    skill: {
        type: String,
        required: [ true, "Skill is required" ]
    },
    severity: {
        type: String,
        enum: [ "low", "medium", "high" ],
        required: [ true, "Severity is required" ]
    }
}, {
    _id: false
})

const preparationPlanSchema = new mongoose.Schema({
    day: {
        type: String,
        required: [ true, "Day is required" ]
    },
    focus: {
        type: String,
        required: [ true, "Focus is required" ]
    },
    tasks: [ {
        type: String,
        required: [ true, "Task is required" ]
    } ]
}, {
    _id: false
})

// Schema matching your Zod structural layout for the AI-tailored resume data
const tailoredResumeSchema = new mongoose.Schema({
    fullName: { type: String, default: 'Candidate Name' },
    email: { type: String, default: '' },
    phone: { type: String, default: '' },
    location: { type: String, default: '' },
    linkedin: { type: String, default: '' },
    github: { type: String, default: '' },
    summary: { type: String, default: '' },
    skills: [{ type: String }],
    experience: [{
        title: { type: String },
        company: { type: String },
        duration: { type: String },
        bullets: [{ type: String }]
    }],
    projects: [{
        name: { type: String },
        tech: { type: String },
        bullets: [{ type: String }]
    }],
    education: [{
        degree: { type: String },
        institution: { type: String },
        year: { type: String }
    }]
}, { _id: false });

const interviewReportSchema = new mongoose.Schema({
    jobDescription: {
        type: String,
        required: [ true, "Job description is required" ]
    },
    resume: {
        type: String,
    },
    selfDescription: {
        type: String,
    },
    matchScore: {
        type: Number,
        min: 0,
        max: 100,
    },
    technicalQuestions: [ technicalQuestionSchema ],
    behavioralQuestions: [ behavioralQuestionSchema ],
    skillGaps: [ skillGapSchema ],
    preparationPlan: [ preparationPlanSchema ],
    
    // Injected into the root document state to hold tailored PDF resume contents
    tailoredResume: tailoredResumeSchema, 

    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "users"
    },
    title: {
        type: String,
        required: [ true, "Job title is required" ]
    },
    
    isPublic: {
        type: Boolean,
        default: false
    }
}, {
    timestamps: true
})

const interviewReportModel = mongoose.model("InterviewReport", interviewReportSchema);

module.exports = interviewReportModel;