
/**
 * @typedef {Object} TechnicalQuestion
 * @property {string} question - The technical question generated by the AI.
 * @property {string} intent - The core concept or intent being tested by this question.
 * @property {string} answer - The expected ideal answer for reference.
 */

/**
 * @typedef {Object} BehavioralQuestion
 * @property {string} question - The behavioral/situational question matching the job role.
 * @property {string} intent - The soft skill or trait being evaluated.
 * @property {string} answer - Suggested structure or points for the response (e.g., STAR method).
 */

/**
 * @typedef {Object} SkillGap
 * @property {string} skill - The specific skill or technology missing from the resume.
 * @property {('low'|'medium'|'high')} severity - The critical impact level of the missing skill relative to the job.
 */

/**
 * @typedef {Object} PreparationDay
 * @property {number} day - The specific milestone or day number in the roadmap.
 * @property {string} focus - The core subject or technical area assigned to this day.
 * @property {string[]} tasks - Array of actionable training steps, readings, or coding exercises.
 */

/**
 * @schema InterviewAnalysisSchema
 * @description Defines the Mongoose/JSON layout tracking user profile metrics parsed against a target job description.
 * * @property {string} jobDescription - Raw text or markdown criteria of the target job posting.
 * @property {string} resumeText - Extracted text profile content from the user's uploaded CV.
 * @property {string} selfDescription - Optional biographical/cover letter text input provided by the applicant.
 * * @property {number} matchScore - Calculated alignment percentage score between 0 and 100.
 * @property {TechnicalQuestion[]} technicalQuestions - Array of custom AI-generated technical interview benchmarks.
 * @property {BehavioralQuestion[]} behavioralQuestions - Array of custom AI-generated behavioral evaluation scenarios.
 * @property {SkillGap[]} skillGaps - Matrix identifying critical missing experience requirements.
 * @property {PreparationDay[]} preparationPlan - An ordered, step-by-step custom curriculum roadmap.
 */


const mongoose = require('mongoose');


const technicalQuestionSchema = new mongoose.Schema({
    question: {
        type: String,
        required: [ true, "Technical question is required" ]
    },
    intention: {
        type: String,
        required: [ true, "Intention is required" ]
    },
    answer: {
        type: String,
        required: [ true, "Answer is required" ]
    }
}, {
    _id: false
})

const behavioralQuestionSchema = new mongoose.Schema({
    question: {
        type: String,
        required: [ true, "Technical question is required" ]
    },
    intention: {
        type: String,
        required: [ true, "Intention is required" ]
    },
    answer: {
        type: String,
        required: [ true, "Answer is required" ]
    }
}, {
    _id: false
})

const skillGapSchema = new mongoose.Schema({
    skill: {
        type: String,
        required: [ true, "Skill is required" ]
    },
    severity: {
        type: String,
        enum: [ "low", "medium", "high" ],
        required: [ true, "Severity is required" ]
    }
}, {
    _id: false
})

const preparationPlanSchema = new mongoose.Schema({
    day: {
        type:String,
        required: [ true, "Day is required" ]
    },
    focus: {
        type: String,
        required: [ true, "Focus is required" ]
    },
    tasks: [ {
        type: String,
        required: [ true, "Task is required" ]
    } ]
})

const interviewReportSchema = new mongoose.Schema({
    jobDescription: {
        type: String,
        required: [ true, "Job description is required" ]
    },
    resume: {
        type: String,
    },
    selfDescription: {
        type: String,
    },
    matchScore: {
        type: Number,
        min: 0,
        max: 100,
    },
    technicalQuestions: [ technicalQuestionSchema ],
    behavioralQuestions: [ behavioralQuestionSchema ],
    skillGaps: [ skillGapSchema ],
    preparationPlan: [ preparationPlanSchema ],
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "users"
    },
    title: {
        type: String,
        required: [ true, "Job title is required" ]
    }
}, {
    timestamps: true
})


const interviewReportModel = mongoose.model("InterviewReport", interviewReportSchema);

module.exports = interviewReportModel;  